### YamlMime:ManagedReference
items:
- uid: System.StackOverflowException
  id: StackOverflowException
  children:
  - System.StackOverflowException.#ctor
  - System.StackOverflowException.#ctor(System.String)
  - System.StackOverflowException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: StackOverflowException
  nameWithType: StackOverflowException
  fullName: System.StackOverflowException
  type: Class
  summary: "A exceção é acionada quando a capacidade excedida da pilha de execução porque contém demasiadas chamadas de método aninhada. Esta classe não pode ser herdada."
  remarks: "StackOverflowException é emitida para erros de excesso de pilha de execução, normalmente em caso de uma recursão muito profunda ou unbounded.       StackOverflowException utiliza o COR_E_STACKOVERFLOW HRESULT, que tem o valor 0x800703E9. O <xref:System.Reflection.Emit.OpCodes.Localloc>instrução de idioma intermédias (IL) emite StackOverflowException.</xref:System.Reflection.Emit.OpCodes.Localloc> Para obter uma lista de valores de propriedade inicial para um objeto de StackOverflowException, consulte o <xref:System.StackOverflowException.%23ctor%2A>construtores.</xref:System.StackOverflowException.%23ctor%2A>      ## Considerações sobre a versão no .NET Framework 1.0 e 1.1, foi possível detetar um objeto de StackOverflowException (por exemplo, para recuperar a partir da recursão unbounded). Começando com o .NET Framework 2.0, não é possível detetar um objeto de StackOverflowException com um `try` / `catch` blocos e o processo de correspondente foi terminada por predefinição. Por conseguinte, deve escrever o seu código detete e impeça uma capacidade excedida da pilha. Por exemplo, se a aplicação depende recursão, utilize um contador ou uma condição de estado para terminar o ciclo de recursiva. O exemplo seguinte utiliza um contador para se certificar de que o número de recursiva chamadas para o `Execute` método não pode exceder um máximo definido pela constante MAX_RECURSIVE_CALLS.       [!code-vb[System.StackOverflowException.Class#1](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)][!code-cs[System.StackOverflowException.Class#1](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs) ]       >  [!NOTE] > Applying o <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>atributo para um método que emite um StackOverflowException não tem qualquer efeito.</xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>   Não é possível processar a exceção a partir do código de utilizador.       Se a sua aplicação aloja o language runtime (CLR), pode especificar que o CLR deve descarregar o domínio de aplicação em que a exceção de capacidade excedida da pilha ocorre e permitir que o processo correspondente continuar. Para obter mais informações, consulte [ICLRPolicyManager Interface](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class StackOverflowException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor
  id: '#ctor'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.StackOverflowException&quot;> </xref> classe, a definição da <xref:System.Exception.Message*>propriedade da instância do novo a uma mensagem fornecido pelo sistema que descreve o erro, tal como &quot;a operação pedida causou uma capacidade excedida da pilha.&quot;</xref:System.Exception.Message*> Esta mensagem tem em consideração o idioma atual do sistema."
  remarks: "A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro localizado. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException ();
    parameters: []
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.StackOverflowException&quot;> </xref> classe com uma mensagem de erro especificado."
  remarks: "A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>que descreve o erro.</xref:System.String> O conteúdo da mensagem se destina a ser compreendidos pela entidade humans. O autor da chamada deste construtor não é necessária para se certificar de que esta cadeia tem foram localizada da cultura atual do sistema."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.StackOverflowException&quot;> </xref> classe com uma mensagem de erro especificado e uma referência a exceção interna que é a causa desta exceção."
  remarks: "Uma exceção que é acionada como um resultado direto de uma exceção anterior pode incluir uma referência a exceção anterior no <xref:System.Exception.InnerException%2A>propriedade.</xref:System.Exception.InnerException%2A> O <xref:System.Exception.InnerException%2A>propriedade devolve o mesmo valor que é transmitido no construtor ou uma referência nula (`Nothing` no Visual Basic) se o <xref:System.Exception.InnerException%2A>propriedade não fornecer o valor da exceção interna para o construtor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A referência a exceção interna. |   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem de erro que explique a razão para a exceção."
    - id: innerException
      type: System.Exception
      description: "A exceção é a causa da exceção atual. Se o `innerException` parâmetro não é uma referência nula (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> no Visual Basic), a exceção atual num <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloco que processa a exceção interna."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.StackOverflowException.#ctor
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
- uid: System.StackOverflowException.#ctor(System.String)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.StackOverflowException.#ctor*
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException
  nameWithType: StackOverflowException.StackOverflowException
